CREATE TABLE usuario(
  uid SERIAL NOT NULL,
  login VARCHAR(20) NOT NULL,
  pwd VARCHAR(50) NOT NULL,
  fullname VARCHAR(200) NOT NULL,
  photopath VARCHAR(300) NOT NULL,
  cpf VARCHAR(11),
  rg VARCHAR(15),
  nametag VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  address VARCHAR(500) NOT NULL,
  logradouro VARCHAR(100) NOT NULL,
  complemento VARCHAR(70) NOT NULL,
  bairro VARCHAR(30) NOT NULL,
  cep VARCHAR(10) NOT NULL,
  city VARCHAR(30) NOT NULL,
  state VARCHAR(20) NOT NULL,
  telresidencial VARCHAR(20),
  telcomercial VARCHAR(20),
  telcelular VARCHAR(20),
  telrecado VARCHAR(20),
  dbirth VARCHAR(10) NOT NULL,
  estadocivil VARCHAR(20) NOT NULL,
  escolaridade VARCHAR(50) NOT NULL,
  profession VARCHAR(50) NOT NULL,
  instorigem VARCHAR(50) NOT NULL,
  usertype INT DEFAULT 1,
  CONSTRAINT pk_usuario PRIMARY KEY (uid),
  CONSTRAINT u_usuario_login UNIQUE (login)
);

